services:
  dev_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base_backend
    ports:
       - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/.venv
    networks:
      - default
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["uv","run","fastapi","run", "api.py", "--host", "0.0.0.0", "--port", "8080","--reload"]
  dev_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base_frontend
    ports:
      - "8081:3000"
    volumes:
      - ./frontend:/app
      - /app/.next
      - /app/node_modules
    environment:
      - LLM_API_URL=${LLM_API_URL}
    networks:
      - default
    command: ["npm","run","dev"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8080:8080"
    networks:
      - default
    develop:
      # Create a `watch` configuration to update the app
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path:  ./backend
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    # stdin_open: true
    # tty: true
    # command:  ["/app/.venv/bin/fastapi","run", "main.py", "--host", "0.0.0.0", "--port", "8080","--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8081:8080"
    networks:
      - default

    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path:  ./frontend
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  postgres:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.postgresdata:/var/lib/postgresql/data
    healthcheck:  # コンテナの起動チェック
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
    networks:
      - default

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FERRETDB_TELEMETRY: disable
    depends_on:
        postgres:
          condition: service_healthy  # postgres がちゃんと起動したら start
    networks:
      - default

networks:
  default:
    name: devnet
    external: true